# Site settings
title: 小强中国
name: 小强中国 # your name
email: sky.craper@foxmail.com # your email address
description: >
    Trying to be A full-stack developer. # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://befullstackdev.github.io" # the base hostname & protocol for your site
twitter_username: @SkyKaiyu # your Twitter username
github_username: kaiyulee # your Github username
disqus_username: kaiyulee # your disqus username

google-analytics:  # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
